### ISSUE TITLE
How to add custom validator?

### ISSUE THREAD

**Issue by sanketsahusoft** [dwightwatson/validating#115]
Great work there! I am using it for a huge project.

I created a ServiceProvider and in the boot method, I added a new resolver for Validation with my own class CustomValidator. And now \Validator::make() returns an object of my CustomValidator but when I do $model->getValidator(), I get the same default Validator.

Any help will be appreciated.

**Comment by dwightwatson** [comment]
You can call `$model->setValidator()` and pass your custom validator through there. 

I'm not that familiar with creating custom validators, but if you have any ideas of how to better support them in the library let me know or feel free to make a PR. :)

**Comment by dwightwatson** [comment]
After sleeping on it, you're probably better off just overriding `getValidator()` in your model and returning your custom validator that way.

**Comment by sanketsahusoft** [comment]
Thanks Dwight! I overrode the `makeValidator()` function, as I had to add
validation messages as well.

**Comment by sanketsahusoft** [comment]
Thanks Dwight! I overrode the `makeValidator()` function, as I had to add validation messages as well.
