### ISSUE TITLE
Validation on pivot tables

### ISSUE THREAD

**Issue by stelgenhof** [dwightwatson/validating#116]
I have a pivot table with additional fields that I would like to have validation applied to. I couldn't find anything regarding this. Would I need to create a model for this pivot table or are there any other options?

**Comment by dalabarge** [comment]
There's a default Laravel model that deals with the pivot tables. I'd suggest you look into defining your own and using that as your pivot table model. You should be able to then do validation on that as well though it may require a PR in order to make Validating package work call it when attaching and syncing. Alternatively like you say, you could create a regular model specifically for the pivot table which helps you manage the extra pivot columns. This is a common approach as it often exposes another resource that is available to RESTful APIs.

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Relations/Pivot.php

**Comment by stelgenhof** [comment]
Thanks! However i tried using a custom PivotTable model but with no success. I couldn't get the validation rules to be triggered when creating or updating a record. Pivot tables work great in that the foreign keys are stored and also any additional attributes are created.

What I am trying to achieve is that during such a create/update event, I can also validate those additional attributes. As an example, I have a start and end date in that pivot table and want to validate that the start date is not greater than the end date.

**Comment by dwightwatson** [comment]
I've not used pivots many times so I can't say much in that regard - I often use an intermediary model instead as they're a lot more flexible. Happy to accept any PRs that would add that sort of functionality however!

**Comment by dalabarge** [comment]
@stelgenhof you'll have to work with this file too: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php Using a trait you can overwrite the behavior of certain pivot related functions like attach/detach/sync, etc. and then do something similar to how Validating listens for saving events. Just add events for attach/detach/sync and then inspect the pivot attributes.

What you're asking for with the pivot tables is definitely possible using a dedicated model (not pivot model) and then just using doing something like:

```php
$a = new AModel()
$a->save();

$c = new CModel();
$c->save();

$b = new BModel();
$b->a_id = $a->id;
$b->c_id = $c->id;
$b->start = Carbon::now();
$b->end = Carbon::now()->addDays(1);
$b->save(); // validation should pass/fail according to BModel's rules

// Pivot relationships can still work - just use BModel for CRUD on the pivot table
$b_start = $a->c_models()->first()->pivot->start; // gotten from forward relationship
$b_end = $c->a_models()->first->pivot->end; // gotten from reverse relationship
var_dump($b_start > $b_end); // false
```

You could do it all in a transaction to ensure it all passes or all fails. Querying should still work if you setup the relationships (checkout http://github.com/esensi/model for a cleaner relationship binding) for belongsToMany between A and C models. Just when you insert the models, be sure to do it on the dedicated model B.

**Comment by stelgenhof** [comment]
Hi @dalabarge,

Thank you for the info! Very useful and I will try it out.

Sacha
