### ISSUE TITLE
How are the merged rulesets implemented with isValid()?

### ISSUE THREAD

**Issue by zeckdude** [dwightwatson/validating#120]
The documentation provides an [example][1]:

    $mergedRules = $post->mergeRulesets('saving', 'creating');

How would that be implemented with the following line (but using the merged rulesets instead of the 'my_custom_rules' ruleset)?

    $post->isValid('my_custom_rules', false);

[1]: https://github.com/dwightwatson/validating/tree/0.10#merging-rulesets

**Comment by dwightwatson** [comment]
Hey, thanks for the ping on Twitter, had a hectic week and haven't had a chance to get to my emails yet.

I suppose it makes sense that the first argument of the method should accept the string name of a ruleset or a set of rulesets to validate with.

    $post->isValid($mergedRules);

I'd be happy to accept a PR that introduces this functionality otherwise I'll try and get to it when things settle down.

**Comment by zeckdude** [comment]
Thanks for the quick response to the tweet. I'll be looking forward to added functionality.

How are the merged rulesets supposed to be used currently if you can't validate against them? Just want to make sure I understand its functionality as it stands.

**Comment by dwightwatson** [comment]
If my memory serves me correctly the `mergeRulesets()` method was originally protected and a later PR made it public. It is just used to perform the merging of rulesets behind the scenes, as it would if you used a custom ruleset for example.

So yeah, effectively that method is useless on it's own.

**Comment by zeckdude** [comment]
Sweet. Thanks for the explanation. All making sense now.

Any chance the feature will be added to the 4.2 branch? Haven't upgraded to 5.0 just yet. :)

**Comment by dwightwatson** [comment]
Yeah it will only be added to 4.2. I took rulesets out of 5 because it has form requests (and because they're an absolute pain to maintain).

**Comment by dwightwatson** [comment]
Cool, this should be available in `0.10.7` now.

**Comment by zeckdude** [comment]
I got an answer relating to this on stackoverflow and the suggested answer on http://stackoverflow.com/questions/28497111/in-laravel-4-how-are-the-merging-rulesets-implemented works.

$post = new Post(Input::all());
$post->setRules($post->mergeRulesets('set_up_all', 'set_up_property_room', 'set_up_property'));
if($post->isValid()) { 
     ///
}

So the new way is now $post->isValid($mergedRules)?

**Comment by dwightwatson** [comment]
Yeah, either option would work, but passing the intended ruleset to `isValid()` now won't override the rules already set on the model, plus it's a much nicer syntax.

**Comment by zeckdude** [comment]
Perfect! I appreciate the quick addition!
