### ISSUE TITLE
ValidatingTrait setMessages causes save() failure

### ISSUE THREAD

**Issue by splondike** [dwightwatson/validating#121]
Using setMessages will cause save() to fail, e.g.:

```php
$validatingModel = new ModelWithValidatingTrait();
$validatingModel->setMessages([
   'email' => 'This should be an email'
]);
$validatingModel->save();
```

This is because there's no instance variable for validationMessages (it's set dynamically by setMessages). This in turn causes the save() method in Eloquent\Model.php to attempt to save a column called validationMessages to the DB.

The fix is simply to add a protected validationMessages instance variable to ValidatingTrait.

**Comment by dwightwatson** [comment]
Adding `$validationMessages` to the trait means that you won't be set the property in your model (it's a fatal error if the trait and the class using it both define the same property). I'm of the belief it would be better to pull the `setMessages()` method from the trait.

**Comment by dwightwatson** [comment]
I'm not really sure if removing a method is a breaking change, considering that it was effectively broken anyway. I think I'll just push this fix out on the `0.10` branch.

**Comment by splondike** [comment]
I think that's reasonable.

**Comment by splondike** [comment]
@dwightwatson You might also want to remove setMessages from the interface.

**Comment by dwightwatson** [comment]
It was removed in the second commit, 89ccbc4.
