### ISSUE TITLE
ValidatingTrait does not work with Accessors

### ISSUE THREAD

**Issue by splondike** [dwightwatson/validating#122]
Laravel has the concept of [Accessors](http://laravel.com/docs/4.2/eloquent), unfortunately they don't work with ValidatingTrait. Imagine I have a csv of emails in a single database column and want to validate the entries:

```php
class ValidatingModel {
   use ValidatingTrait;
   protected $rules = array(
      'emails' => array(
         'array',
         'each' => 'email'
      )
   );
   public function getEmailsAttribute($value) {
      return explode(',', $items);
   }
   public function setEmailsAttribute($items) {
      $this->attributes['emails'] = implode(',', $items);
   }
}
```

This model won't be validated correctly as the makeValidator method uses getModel()->getAttributes() which bypasses the accessor. I think validating against the accessors is the right thing to do, however it is a potentially backward incompatible change.

If you take on this suggestion, then I think makeValidator needs to iterate over the keys of its rules and call getAttribute for each of them. This covers the accessor case, and also lets us validate relationships.

If we go with the above solution, then when iterating the rule keys, be sure to test with having rules which validate indexed array elements (e.g. 'emails.1' => 'regex:somewhere.com$'). The solution might be to truncate the key after the first period character. Also, we can't just use attributesToArray, it can potentially hide user specified fields which isn't what we want.

**Comment by splondike** [comment]
The validation case I provided above doesn't work in vanilla Laravel (the each thing doesn't work).

**Comment by dwightwatson** [comment]
This has been discussed before in #69.

It's a tricky issue. The idea of looping through `$rules` keys and fetching the attribute value is a good solution, but this could have some unintended effects for existing users. I'd probably be happy to consider this for the Laravel 5 branch but I'm not too keen to go adding additional functionality to the 4.2 branch.

**Comment by splondike** [comment]
Yeah, it's not a completely safe change. I would consider it for the 5.0 branch though, I think the main point of the accessors for people using your package would be deserialization. In this case validating the deserialized structure would be more useful than the serialized one.
