### ISSUE TITLE
How to display Custom Message for Rule

### ISSUE THREAD

**Issue by urmila-patel** [dwightwatson/validating#123]
How to display Custom Message for Rule

I have added in Model like

 'location' => 'required|min:5',
    'area' => 'required',
    'price' => 'required|numeric'
];

protected $messages = [
    'location.required' => 'A My Location is required',
    'location.min' => 'Location should be longer. Min 3 characters'
];
But Custom Message is not display

What is the Extra Setting Required For Custom Message

**Comment by dwightwatson** [comment]
I've added the validation messages property back. You'll need to run `composer update` to get the new build (`0.10.9`) and change the property to `$validationMessages`.

**Comment by urmila-patel** [comment]
Hello,
I m using it in my Model like 

    protected $rules = [
        'location' => 'required|min:5',
        'area' => 'required',
        'price' => 'required|numeric'
    ];

    protected $validationMessages = [
        'location.required' => 'Empty Location',
        'location.min' => 'Location should be longer. Min 3 characters'
    ];
But Error is like
ErrorException in ValidatingTrait.php line 129:
Undefined variable: validationMessages

**Comment by dwightwatson** [comment]
Dammit, I knew I should have written a test for that. I thought it was too simple to get wrong.

Build `0.10.10` has just been pushed.

**Comment by urmila-patel** [comment]
Thank You...
