### ISSUE TITLE
Validation Rule Not called For Update 

### ISSUE THREAD

**Issue by urmila-patel** [dwightwatson/validating#124]
In Model define the rules.
1. When i try to add ...Error Message Coming
2. Save Called for Update then getError gives me blank result

Please Provide if any setting required for validation when update.....find and then Save

**Comment by dwightwatson** [comment]
You'll need to provide some more sample code for me to understand what is going on here; your model and the relevant controller action would help.

**Comment by urmila-patel** [comment]
My model have code like

 protected $rules = [
        'location' => 'required|min:5',
        'area' => 'required',
        'price' => 'required|numeric'
    ];

    protected $validationMessages = [
        'required' => 'A :attribute is required',
        'location.min' => 'A Location should be longer. Min 3 characters'
    ];

and test case like 

public function testRequirementSave() {
        $req = new \App\Requirement();
        $req->location = 'L1';
       $req->area = 'Area';

        if ($req->save()) {
            $this->assertTrue(true);
        } else {
            $errors = $req->getErrors()->all();
            print_r($errors);

            $this->assertFalse(false);
        }
    }

    public function testRequirementUpdateSave() {

        $req = Requirement::find(24);

        $req->location = 'L2';
        $req->area = 'Area';
        $req->price = '';

        if ($req->save()) {
            $this->assertTrue(true);
        } else {
            $errors = $req->getErrors()->all();
            print_r($errors);

            $this->assertFalse(false);
        }
    }

then phpunit result like

.<a href="fb/login">Login With FB</a>.Array
(
    [0] => A Location should be longer. Min 3 characters
    [1] => A price is required
)
.Array
(
)

So, In update its save data with out errors..

**Comment by dwightwatson** [comment]
Ah okay, this is actually a bug in Laravel which affects the way you test multiple model events. In effect during testing model events are only sent once so any tests after the first event will fail. Read more about it in the [documentation, along with a solution for your `TestCase.php` here](https://github.com/dwightwatson/validating#testing).

I'll close this for now as that appears to be the issue, however please let me know if you have further issues.

**Comment by urmila-patel** [comment]
I Found One Solution

create one environment variable   :   'fwtestmode' => 'false'

In my TestCase.php set that variable like:
  public function setUp()
    {
        parent::setUp();
        Config::set('app.fwtestmode', 'true');
    }

and then in model check that variable and based on that flush the event listener :

 public function save(array $options = array())
    {
        $config = Config::get('app.fwtestmode');

        if ($config == 'true') {
 
            parent::flushEventListeners();
            parent::boot();
        }
}

So, Its working for for multiple Save ....Validation are working
Hope that may be its useful to you.
