### ISSUE TITLE
How to validate an extra pivot table field

### ISSUE THREAD

**Issue by Propaganistas** [dwightwatson/validating#125]
Hi,

I have this many-to-many relation set up in a model:

```
public function pages()
{
    return $this->belongsToMany('App\Models\Page')
                ->withPivot('order');
}
```

How can I validate the `order` property of the pivot table (since it is not directly available in both models) using model validation supplied by this package?

Thanks.

**Comment by dwightwatson** [comment]
The best solution here would be to use a pivot model which then has it's own relations. I'll keep this open as there might be potential for this sort of thing in the future.
