### ISSUE TITLE
Different Rulesets?

### ISSUE THREAD

**Issue by jcrawford** [dwightwatson/validating#136]
I have begun to use this validation library and have a question on how I can have different rulesets for different controller actions.  I ask because we have a createUser action and an editUser action.  On the createUser action we require the password to be filled in otherwise validation will fail.

However on the editUser action we only require the password sometimes.

I see that you have different rules for different rulesets based on model events ```creating```, ```saving```, etc.  I also see that I can have a custom ruleset via name and check $model->isValid('my_custom_ruleset') however is there a way to do this without having to have too much of this validation checking in my controller?

Currently I am just using $model->save() and validation is working but again I don't want to have the rule for the password to be sometimes upon registration only when editing the page.

I should also note that I am using the version for Laravel 4.2 and not 5.1

**Comment by dwightwatson** [comment]
If you wanted to achieve a custom ruleset for a controller action without actually calling the name of a custom ruleset, you might consider creating subclasses of your model for that action. This is just an idea, and one of probably a few ways you could go about it.

    class User extends Model
    {
        // Make sure the correct table is used by subclasses.
        protected $table = 'users';
    }

    class UpdateUser extends User
    {
        protected $rules = [
            // Update rules.
        ];
    }

Then the only thing that need change in your controller is the model class you load.

Personally, I'd probably go with just using the custom ruleset as I think it provides a clearer indication of what is happening when you look through your code. I hope this helps!

The complications that arose from event-based rulesets and custom rulesets is why they were dropped in the version for Laravel 5.x.

**Comment by jcrawford** [comment]
Sorry let me explain a bit better what I am trying to do, I think I may have confused you as well as myself since I am new to Laravel :)

We have a User Model where password has the following ruleset

```'password'                      => 'sometimes|required|different:email_address|min:8|brio_password',```

This works fine for when we are editing users, etc but when creating users or when users register I do not wish to have the "sometimes"  This was put in place originally to stop it from being required when users edit their profiles or when an admin edits a user.  However with it always being there it now allows for users to register without supplying or validating a password which is not a good situation.

What I am looking to do is have different rules for the password element on Creation or Updating of a record.

**Comment by dwightwatson** [comment]
That just sounds like a perfect use case for the 'creating' and 'updating' rulesets though. Place the default rules into the 'saving' ruleset and then place your password rule under 'creating' so it will only apply when a user is created. When creating a model, it will merge the 'creating' rules with the 'saving' rules.
