### ISSUE TITLE
Using Handler.php

### ISSUE THREAD

**Issue by LourensThalen** [dwightwatson/validating#139]
The last bit of code in the readme is not up to date, since App::error is now removed and rewritten into Handler.php.

This would be the new function... :)

    public function render($request, Exception $e)
    {
        if ($e instanceof \Watson\Validating\ValidationException) {
            return Redirect::back()
                ->withErrors($e)
                ->withInput();
        }
    }

Love having my rules in the model, makes my code so much cleaner (and easier to read). Thank you.

**Comment by dwightwatson** [comment]
Cool, thanks for letting me know. Updated the docs to reflect this, and used the Laravel 5 `back()` helper function.
