### ISSUE TITLE
Event listener on L5

### ISSUE THREAD

**Issue by JavoByte** [dwightwatson/validating#145]
Hi. I'm trying to attach an event listener to the validating event but I do not find out how. I copy&pasted the code for `Event::listen` and the `$observables` array in my model. Yet, the event is not being handled properly. What am I missing. I'm using Laravel 5.1.24

**Comment by dwightwatson** [comment]
Whoops, looked like an issue with the docs. I've fixed it up now.

The event you should listen for is actually `eloquent.validating:*` - not the use of a colon instead of a period before the asterisk.
