### ISSUE TITLE
Calling saveOrFail on Model causes infinite loop

### ISSUE THREAD

**Issue by gurminder** [dwightwatson/validating#149]
Line 295    -    return $this->getModel()->saveOrFail($options); 

Calling saveOrFail method on the model causes infinite loop because line 295 keeps calling the same method back on the model.

**Comment by dwightwatson** [comment]
Whoops - that code for `saveOrFail()` was in response to #146 to fix an issue with an upcoming version of Laravel adding a `saveOrFail()` method itself. A new version should not have been tagged.

I've pushed a new version that should resolve this.
