### ISSUE TITLE
Call to member function make() on a non-object online 360

### ISSUE THREAD

**Issue by karneaud** [dwightwatson/validating#158]
Hello,

I'm using standalone Eloquent with Validation trait with following class

```
use Watson\Validating\ValidatingTrait;

class User extends Illuminate\Database\Eloquent\Model {

    use ValidatingTrait;

    protected $table = "users";
    public $timestamps = false;
    protected $rules = [
        'name'   => 'required',
        'phone'    => 'required',
        'email' => 'required',
        'zone' => 'required'
    ];
    protected $validationMessages = [
        'name.required' => 'Please enter your name'
    ];
    protected $fillable = ['name','zone','email','phone'];

```

When I do

`$user = new User(["attr"=>1,......]); $user->isValid();`

I get subject error. I'm not that familiar with eloquent but not sure what it means. Do I need to formulate my own Validate::make()?

**Comment by dwightwatson** [comment]
Can you include the full error that you're getting?

Also, are you using Eloquent outside of the Laravel framework?

**Comment by karneaud** [comment]
> **Can you include the full error that you're getting?
**
> PHPUnit 4.7.6 by Sebastian Bergmann and contributors.
> 
> Runtime errorPHP Fatal error:  Call to a member function make() on a non-object in /Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/vendor/watson/validating/src/ValidatingTrait.php:360
> PHP Stack trace:
......... 
> PHP  13. User->isValid() /Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/tests/users/UserModelStubTest.php:10
> Runtime errorPHP  14. User->performValidation() /Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/vendor/watson/validating/src/ValidatingTrait.php:237
> PHP  15. User->makeValidator() /Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/vendor/watson/validating/src/ValidatingTrait.php:380
> 
> Fatal error: Call to a member function make() on a non-object in /Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt/vendor/watson/validating/src/ValidatingTrait.php:360
> 
> 


> **Also, are you using Eloquent outside of the Laravel framework?**
Yes. I am :-)

**Comment by dwightwatson** [comment]
Hm, this is a little related to #132 too then. Because the facades are not instantiated outside of the Laravel framework, this doesn't work as expected. This is how we get a new instance of a validator...

```
/**
 * Get the Validator instance
 *
 * @return \Illuminate\Validation\Factory
 */
public function getValidator()
{
    return $this->validator ?: Validator::getFacadeRoot();
}
```

Now, this is totally untested, but if you were to set the `validator` property yourself I think you might be able to get this to work. Where you would add it is up to you, you might want to add it in the `boot()` method or something, but this might do the trick

```
$this->validator = new \Illuminate\Validation\Factory;
```

Let me know if this makes sense. You're just bypassing the facade and providing the validator factory manually. No idea if it will work as expected, I've never tried to use Eloquent outside of Laravel.

**Comment by karneaud** [comment]
Tried your solution but started giving me another error of

> Argument 1 passed to Illuminate\Validation\Factory::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface

**Comment by dwightwatson** [comment]
Whoops, needs to be resolved. If you're not using the Laravel IoC container as well then you're going to need to manually pass in the dependencies of the Factory.

**Comment by karneaud** [comment]
I'm using Eloquent as a standalone. Not much of a Lavarel guy but

`new Factory(new Translator('en'));`

seemed to work

**Comment by dwightwatson** [comment]
Ah sorry, the container would just new up the dependencies for you. I'm glad passing in a translator manually did the trick, that's good to know.

**Comment by karneaud** [comment]
Meh...apparently it didn't as I get a 

> facade root has not been set

error

**Comment by karneaud** [comment]
Figured it out using [this article](http://www.sitepoint.com/how-laravel-facades-work-and-how-to-use-them-elsewhere/)
