### ISSUE TITLE
Validation should run on model attributes via getters

### ISSUE THREAD

**Issue by DSpeichert** [dwightwatson/validating#159]
We have multiple fields in our database that are encrypted/decrypted using `Crypt` in getXAttribute/setXAttribute.

We need to limit the length of a sensitive field using e.g. `between:4,32`. The encrypted value is, obviously, much longer. This always fails validation. This validation library should utilize the magic built-in getters to find proper value.

**Comment by dwightwatson** [comment]
Sorry for the delay in getting back to you, been a little caught up.

This makes sense, though it will most likely impact backwards compatibility.

At the moment we get the model attributes with `getAttributes()` which returns them as they come from the database. I'm not sure there a method that gets all the model attributes using custom accessors where defined (I just had a quick look, I could have missed something).

I suppose we could call `getAttributes()`, then loop through the keys in that array calling `getAttribute()` on each one to use the accessors if they exist, though this would have a performance hit.

You could try this out using this overriding method in your application.

```
    /**
     * Get the casted model attributes.
     *
     * @return array
     */
    public function getModelAttributes()
    {
        $attributes = $this->getModel()->getAttributes();

        foreach ($attributes as $key => $value) {
            $attributes[$key] = $this->getAttributeValue($key);
        }

        return $attributes;
    }
```

I just tried it, and it is breaking the tests as I expected, but it's something I'll look at a little more closely when I have some time. If you do give a shot please let me know how you go!

**Comment by dwightwatson** [comment]
We actually looped through the attributes already to check for casts, not that much extra work to check for accessors as well. I've got this working with additional tests for it on my local machine, might push it to `master` a little later. I suspect I'd have to bump the version to `3.0.0` to release it though.

**Comment by DSpeichert** [comment]
Thanks @dwightwatson!
It seems to be working well now.

**Comment by dwightwatson** [comment]
This went out in `2.1.0` I believe.
