### ISSUE TITLE
Handling Multiple Forms on a Single Page

### ISSUE THREAD

**Issue by mikebronner** [dwightwatson/validating#16]
I've been thinking this should be possible through some simple additions:
- If the validated form has a name, create a bucket for the form using the form's name, and use that as the message bucket in addition to adding all messages in the general bucket (for when the user has a form name, but doesn't use the named message bucket).

This way one could access the errors for their form via something like:

``` php
$errors->myFormName->first('fieldName', '<span class="help-block col-sm-4">:message</span>');
```

as well as the traditional route.
(See "Named Error Bag" in this section: http://laravel.com/docs/validation#error-messages-and-views).

Or has this already been implemented? (I assumed not, since it wasn't documented.)
Thoughts?

**Comment by Cyrille37** [comment]
Another way, if you don't want to return to the client, you can set the error bag's name

```
        try {
            $post->save();
        }
        catch( ValidationException $ex )
        {
            // Set a specific error messageBag
            $ex->errorBag('document');
            throw $ex ;
        }
```
