### ISSUE TITLE
after date validation broken

### ISSUE THREAD

**Issue by lostincode** [dwightwatson/validating#162]
I'm not sure when this happened, maybe https://github.com/dwightwatson/validating/commit/caadc57abd0ae95f99db4dbe058d64aa3b593592

2.1.0 works, 2.1.1 breaks the following validation rule

`required|date|after:start_date`

passes an instance of Carbon to the function, rather than the required string (which always returns false)

Illuminate\Validation
```php
protected function validateAfter($attribute, $value, $parameters)
```

**Comment by dwightwatson** [comment]
Hey, sorry about this, will have to account for this.

I'm assuming that you've got `start_date` set in your model's `$dates` property?

Maybe I should cast the value back to a string before passing it to the validator? I'm not sure if this will have any more side effects though.

**Comment by dwightwatson** [comment]
Would you mind replacing the code with this and seeing if it resolves the issue for you?

```
foreach ($attributes as $key => $value) {
    $value = $this->getModel()->getAttributeValue($key);

    $attributes[$key] = is_array($value) ? $value : (string) $value;
}
```

**Comment by lostincode** [comment]
Sure! I was going to look more into this anyway. Re: $date prop / model attribute, yes.

That change seemed to work and seems to work well :+1:

**Comment by dwightwatson** [comment]
Think I've got a better solution for this in `master` now, it's aware of `Carbon` casts and handles them appropriately. It's mucked up tests on PHP 5.4 though, so I'll sort that out and try and get a tagged release out today.

**Comment by lostincode** [comment]
@dwightwatson sweet, thanks! Let me know if I can help assist in anyway!
