### ISSUE TITLE
Problem with casting

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [dwightwatson/validating#170]
My model uses casting data atribute to/from array

    protected $casts = [
        'data' => 'array',
    ];

The rule is that data must be a string.

    protected $rules = [
        'data' => 'required|string',
    ];

So the problem is that validation is happening before the attribute is being cast. It throws Watson\Validating\ValidationException with the error:

    Illuminate\Support\MessageBag {#909
      #messages: array:1 [
        "data" => array:1 [
           0 => "The data must be a string."
        ]
      ]
      #format: ":message"
    }

I had a quick look on how it works and found that it performs validation on the 'saving' Laravel event.

    public function saving(Model $model)
    {
        return $this->performValidation($model, 'saving');
    }

Laravel fires 'saving' event before other manipulations

    public function save(array $options = [])
    {
        $query = $this->newQueryWithoutScopes();

        // If the "saving" event returns false we'll bail out of the save and return
        // false, indicating that the save failed. This provides a chance for any
        // listeners to cancel save operations if validations fail or whatever.
        if ($this->fireModelEvent('saving') === false) {
            return false;
        }
    ............

Am I right? And what can I do?

Thanks

**Comment by dwightwatson** [comment]
No - the validator runs through any casts before validating the data. It will have cast your `data` attribute to an array, which means it fails when you try to validate it as a string. It's not possible to cast an array as a string. 

If you wanted to validate that the casted array is an array of strings, you would probably need to write a custom validator for that. I don't think Laravel's array-style validators will work for you, but you could try them. Something like `'data.*' => 'string`, but I could be wrong. I hope this helps!

**Comment by KonstantinKolodnitsky** [comment]
Thank you.

**Comment by KonstantinKolodnitsky** [comment]
Sorry, but I'm not satisfied with the answer.

Laravel docs suggests

    When you set the value of the options attribute, the given array will automatically be serialized back into JSON for storage:

So after casting the option attribute is a string(json) and can be validated as a string. Isn't it?

**Comment by dwightwatson** [comment]
No, this library is validating attributes as they exist on an instance of a model. You are validating against the PHP array. The fact that Laravel serializes it as a JSON string under the hood should not be a consideration here - it's an implementation detail of Eloquent when rather you want to be validating the contents of that array.

**Comment by KonstantinKolodnitsky** [comment]
Aha, now I've got it!
Absolutely support the approach.
Thanks
