### ISSUE TITLE
Add how to use multiple rules to readme.md

### ISSUE THREAD

**Issue by dels07** [dwightwatson/validating#173]
Currently readme.md don't show how to use rulesets property to set multiple rules for creating, updating and saving.

**Comment by dwightwatson** [comment]
The latest version doesn't allow different rule sets based on the event. The last major release did, but hasn't been tested for compatibility with Laravel 5.x. Feel free to look into the older version if that is something you need.

**Comment by dels07** [comment]
So how to set different rules when creating/updating?
