### ISSUE TITLE
Override validation rules on delete

### ISSUE THREAD

**Issue by IvanRibakov** [dwightwatson/validating#178]
Is there a way to override default model rules **on delete**, for example to perform foreign key integrity checks (only allow record deletion if hasMany relations are empty)? 

Obviously, these kind of checks don't make sense on insert/update, hence the question about overriding default model rules.

**Comment by dwightwatson** [comment]
If you're using the version pre-Laravel 5.3 then it did support using different rules for different events, but for 5.3+ you can use the `setRules` method to override the rules when you need. You could create a method on your model that sets the rules necessary for deletion and then performs the deletion. Hope this helps!

**Comment by IvanRibakov** [comment]
Thanks for your reply. Could you please confirm whether plugin is able to handle validation of the relations? If I understand correctly, in ValidatingTrait.php line 365 only direct model attributes are passed to validator (but not any of the relationships).

**Comment by dwightwatson** [comment]
Nope - each model only looks after it's own validation and not that of it's relationships. It's a neat idea, but something I'm unlikely to implement. Now that Laravel ships with form requests as a validation method I usually recommend going down that path instead.

**Comment by IvanRibakov** [comment]
I see. It might help save others some time if you mentioned this limitation somewhere in the readme. Without list of supported rules one assumes that all validation rules provided by Laravel (including `size`) are supported by this plugin. Thanks for taking your time to reply!

**Comment by dwightwatson** [comment]
All validation rules do work though? It's that when you validate a model it won't attempt to validate any model relations it has as well, and I'm not sure that's expected functionality anyway.
