### ISSUE TITLE
LogicException with last release v3.1.0

### ISSUE THREAD

**Issue by Omranic** [dwightwatson/validating#187]
After upgrading to **v3.1.0**, and trying to save a model we get `LogicException thrown with message "Model::validationMessages must return a relationship instance."`.

This issue doesn't exist with prior versions **v3.0.X** & **v2.X.X**

Any suggestions?

**Comment by Thijmen** [comment]
Same here too.

**Comment by dwightwatson** [comment]
Sorry about this, it was added by in a PR over the weekend. Are you doing anything out of the ordinary, or would you be able to share any code that is causing this issue for you? If I can replicate it I'll see if I can put a fix in place otherwise I'll roll it back.

**Comment by dwightwatson** [comment]
Wait, nevermind. It was pretty easily to replicate. On it now.

**Comment by dwightwatson** [comment]
I've just pushed out `3.1.1` with a fix for this - please let me know if you run into any other issues. Again sorry about all of this.
