### ISSUE TITLE
2.2.2 error happend

### ISSUE THREAD

**Issue by ZeroCenter** [dwightwatson/validating#189]
~~~~
<?php 
namespace models;
use Watson\Validating\ValidatingTrait;
class Task extends Base{ 


		use ValidatingTrait;

		protected $rules = [
			'title'   => 'required',
			'slug'    => 'required|unique:posts,slug',
			'content' => 'required'
		];
~~~~

~~~~
 $m = new Task;
  $m->save();
~~~~

when save show errors
~~~~
atal error: Uncaught Error: Call to a member function until() on null in  illuminate\support\Facades\Facade.php on line 213
~~~~

**Comment by dwightwatson** [comment]
I'm going to need a lot more context here - it's not even clear that this error has anything to do with this package. I don't believe we have any methods called `until()`. Please provide enough code to reproduce the error and upgrade to a newer release of the package - we're up to 3.x now.

**Comment by ZeroCenter** [comment]
i am used it outside,not in laravel ,maybe this is problem.thanks
