### ISSUE TITLE
Objects or closures in rules unsupported

### ISSUE THREAD

**Issue by Propaganistas** [dwightwatson/validating#200]
Hi

A rather important heads up: according to the official [docs](https://laravel.com/docs/5.6/validation#custom-validation-rules) Laravel also supports Rule objects and closures in a rules array:

```php
use App\Rules\Uppercase;

$rules = [
    'required',
    new Uppercase,
    function($attribute, $value, $fail) {
        if ($value === 'foo') {
            return $fail($attribute.' is invalid.');
        }
    },
];
```

The package currently errors  in the `injectUniqueIdentifier()` method. When exploding the rule, it is assumed the rule is always a string:
```php
$parameters = explode(':', $rule);
```

I just ran into this issue and thought I'd let you know. I'm not sending in a PR; seems a rather easy fix to me so go ahead.

**Comment by dwightwatson** [comment]
Thanks for reporting this. Unfortunately I don't have the time to dedicate to fixing this implementation at the moment but I'm happy to accept any PR that can sort it out.
