### ISSUE TITLE
custom validator

### ISSUE THREAD

**Issue by maxdiable** [dwightwatson/validating#201]
it's possible to create a custom validator, 
any example ??

br
Max

**Comment by dwightwatson** [comment]
I don’t understand the question, could you give some more context as to what you’re trying to achieve?

**Comment by maxdiable** [comment]
hi, I would like to create a custom validation, for example I would like to check that a precise code is selected in an input field of the page, it's possible ?
br
Max

**Comment by dwightwatson** [comment]
Yes, just write a custom validation rule. The Laravel docs show you how to do this. Then just add your rule to the rules array on the model. This library just uses Laravel’s validation under the hood. Let me know if you have any issues with this.

**Comment by maxdiable** [comment]
I tried to understand how to make a custom rule and associate it with the rules of your plugin, but I can not figure out how to do it, I will try to do other tests.

br
Max

**Comment by dwightwatson** [comment]
I'm not sure how more I can help apart from writing the code for you. Look at this page to see how to write custom validators for Laravel - using classes or extensions (you can't use the closure syntax with this package at this stage): https://laravel.com/docs/5.6/validation#custom-validation-rules

Then you just add those new rules to the `$rules` array on the model you want to validate. It would work just the same as if you were using Laravel's validator by itself.

**Comment by dwightwatson** [comment]
Actually it's possible that only the validator extensions work at the moment (not classes or closure syntax: #200).
