### ISSUE TITLE
Custom validation rule in the model

### ISSUE THREAD

**Issue by snuzi** [dwightwatson/validating#214]
Hi there,
I found this library very useful, but I am finding it very difficult to set some custom rules in the model. 
Ex: I have an attribute `keywords` which should store some keywords comma separated "word1,word2". 
I want to have make a function to perform a custom rule for keywords attribute. I could find a workaround to put the custom validation rule in the controller (rest API response) like:
`$request-> validate(['keywords' => new MyValidation()])`

I would appreciate if this library supports that case, or if anyone managed to make it work in the model.
Thanks

**Comment by dwightwatson** [comment]
I think this is the same issue as #177 - where this library validates content through accessors/mutators rather than the request input or raw database data. This is unlikely to change any time soon I'm afraid, but discussion can continue in the other issue.
